---
- name: Add NGINX apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add NGINX repo (Debian)
  apt_repository:
    repo: deb http://nginx.org/packages/debian/ stretch nginx
    state: present
    filename: nginx
  when: ansible_distribution == 'Debian'

- name: Add NGINX repo sources (Debian)
  apt_repository:
    repo: deb-src http://nginx.org/packages/debian/ stretch nginx
    state: present
    filename: nginx
  when: ansible_distribution == 'Debian'

- name: Add NGINX repo (Ubuntu)
  apt_repository:
    repo: deb https://nginx.org/packages/mainline/ubuntu/ bionic nginx
    state: present
    filename: nginx
  when: ansible_distribution == 'Ubuntu'

- name: Add NGINX repo sources (Ubuntu)
  apt_repository:
    repo: deb-src https://nginx.org/packages/mainline/ubuntu/ bionic nginx
    state: present
    filename: nginx
  when: ansible_distribution == 'Ubuntu'


- name: Remove previous versions of nginx
  apt:
    name: nginx
    state: absent

- name: Remove previous versions of nginx-common
  apt:
    name: nginx-common
    state: absent
    
- name: Install nginx
  apt:
    name:
      - nginx
    state: latest
    update_cache: yes

- name: Ensure sites-enabled folder is present
  become: true
  file:
    dest: /etc/nginx/sites-enabled
    state: directory

- name: Ensure sites-available folder is present
  become: true
  file:
    dest: /etc/nginx/sites-available
    state: directory


- name: Ensure include of sites-enabled is present in nginx config file
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    insertafter: 'include /etc/nginx/conf\.d/\*\.conf;'
    line: '    include /etc/nginx/sites-enabled/*;'

- name: Ensure access log can be read
  file:
    path: /var/log/nginx/access.log
    mode: '0644'

- name: Ensure error log can be read
  file:
    path: /var/log/nginx/error.log
    mode: '0644'

- name: reload systemd config
  systemd:
    daemon_reload: yes

- name: Ensure nginx is started
  service:
    name: nginx
    state: restarted
    enabled: yes
